site_name: PoolFlow
repo_url: https://github.com/victorgarric/PoolFlow
site_author : Victor Garric

theme:
    name: "material"
    custom_dir: docs/overrides
    logo: assets/pool.png
    features:
      - navigation.indexes
      - toc.integrate
      - toc.follow
      - navigation.sections
      - navigation.top
      - content.tabs.link

    palette:

    # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
      - toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            merge_init_into_class: True
            members_order: 'source'
            group_by_category: True
  - search
nav:
  - Home: index.md
  - testing.md
  - tutorials.md
  - References:
    - reference.md
    - StaticPool : staticpool.md
    - DynamicPool : dynamicpool.md
    - ServerPool : serverpool.md
    - Utilities : utilities.md



markdown_extensions:
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list